o added an "-adm" option that runs an adjoint test instead of the normal    forward tests    - confirmed to work with global_ocean.90x40x15 in checkpoint52a_post      since the current HEAD seems to be broken for the adjoint    - used staf for the above test    - produces same results for the forward tests

diff --git a/verification/testreport b/verification/testreport
--- a/verification/testreport
+++ b/verification/testreport
@@ -1,6 +1,6 @@
 #! /usr/bin/env bash
 #
-#  $Header: /u/gcmpack/MITgcm/verification/testreport,v 1.23 2003/11/29 01:45:25 edhill Exp $
+#  $Header: /u/gcmpack/MITgcm/verification/testreport,v 1.24 2003/11/30 01:28:51 edhill Exp $
 #  $Name:  $
 #
 
@@ -22,6 +22,7 @@ usage()
     echo "  (-b|-bash) STRING        preferred location of a \"bash\" or"
     echo "                             Bourne-compatible \"sh\" shell"
     echo "                             (DEF=\"\" for \"bash\")"
+    echo "  (-adm|-ad)               perform an adjoint run"
     echo "  (-command) STRING        command to run"
     echo "                             (DEF=\"make output.txt\")"
     echo "  (-m|-make) STRING        command to use for \"make\""
@@ -148,38 +149,56 @@ dashnum()
     done
 }
 
+testoutput_ad()
+{
+    grep $3 $1/results_ad/output.txt_adm | awk '{print NR " " $5}' > t05.txt
+    grep $3 $1/$2/output.txt_adm | awk '{print NR " " $5}' > t15.txt
+    grep $3 $1/results_ad/output.txt_adm | awk '{print NR " " $6}' > t06.txt
+    grep $3 $1/$2/output.txt_adm | awk '{print NR " " $6}' > t16.txt
+    join t05.txt t15.txt > t5.txt
+    join t06.txt t16.txt > t6.txt
+    echo "-1" >> t5.txt
+    echo "-1" >> t6.txt
+    digits_5=`./tmp_cmpnum < t5.txt`
+    digits_6=`./tmp_cmpnum < t6.txt`
+    dashnum $digits_5 $digits_6
+    rm -f t[01][56].txt t[56].txt
+}
+
 testoutput()
 {
-    # testoutput diretory subdir
+    # testoutput directory subdir
     #
     #  test output in "directory"
-
-    if [ $debug -gt 0 ]; then
-	echo testoutput: testoutput_for_prop $1 cg2d_init_res 1>&2
+    if test "x$ADM" = x ; then
+	if [ $debug -gt 0 ]; then
+	    echo testoutput: testoutput_for_prop $1 cg2d_init_res 1>&2
+	fi
+	testoutput_for_prop $1 "cg2d_init_res" "cg2d init. residual" $2; cg2dres=$?
+	if [ $debug -gt 0 ]; then
+	    echo testoutput: cg2dres=$cg2dres 1>&2
+	fi
+	testoutput_for_prop $1 "dynstat_theta_min" "theta minimum" $2; tmin=$?
+	testoutput_for_prop $1 "dynstat_theta_max" "theta maximum" $2; tmax=$?
+	testoutput_for_prop $1 "dynstat_theta_mean" "theta mean" $2; tmean=$?
+	testoutput_for_prop $1 "dynstat_theta_sd" "theta s.d." $2; tsd=$?
+	testoutput_for_prop $1 "dynstat_salt_min" "salt minimum" $2; smin=$?
+	testoutput_for_prop $1 "dynstat_salt_max" "salt maximum" $2; smax=$?
+	testoutput_for_prop $1 "dynstat_salt_mean" "salt mean" $2; smean=$?
+	testoutput_for_prop $1 "dynstat_salt_sd" "salt s.d." $2; ssd=$?
+	testoutput_for_prop $1 "dynstat_uvel_min" "U minimum" $2; umin=$?
+	testoutput_for_prop $1 "dynstat_uvel_max" "U maximum" $2; umax=$?
+	testoutput_for_prop $1 "dynstat_uvel_mean" "U mean" $2; umean=$?
+	testoutput_for_prop $1 "dynstat_uvel_sd" "U s.d." $2; usd=$?
+	testoutput_for_prop $1 "dynstat_vvel_min" "V minimum" $2; vmin=$?
+	testoutput_for_prop $1 "dynstat_vvel_max" "V maximum" $2; vmax=$?
+	testoutput_for_prop $1 "dynstat_vvel_mean" "V mean" $2; vmean=$?
+	testoutput_for_prop $1 "dynstat_vvel_sd" "V s.d." $2; vsd=$?
+	dashnum $cg2dres $tmin $tmax $tmean $tsd $smin $smax $smean $ssd \
+	    $umin $umax $umean $usd $vmin $vmax $vmean $vsd
+    else
+	testoutput_ad $1 $2 "precision_grdchk_result"
     fi
-    testoutput_for_prop $1 "cg2d_init_res" "cg2d init. residual" $2; cg2dres=$?
-    if [ $debug -gt 0 ]; then
-	echo testoutput: cg2dres=$cg2dres 1>&2
-    fi
-    testoutput_for_prop $1 "dynstat_theta_min" "theta minimum" $2; tmin=$?
-    testoutput_for_prop $1 "dynstat_theta_max" "theta maximum" $2; tmax=$?
-    testoutput_for_prop $1 "dynstat_theta_mean" "theta mean" $2; tmean=$?
-    testoutput_for_prop $1 "dynstat_theta_sd" "theta s.d." $2; tsd=$?
-    testoutput_for_prop $1 "dynstat_salt_min" "salt minimum" $2; smin=$?
-    testoutput_for_prop $1 "dynstat_salt_max" "salt maximum" $2; smax=$?
-    testoutput_for_prop $1 "dynstat_salt_mean" "salt mean" $2; smean=$?
-    testoutput_for_prop $1 "dynstat_salt_sd" "salt s.d." $2; ssd=$?
-    testoutput_for_prop $1 "dynstat_uvel_min" "U minimum" $2; umin=$?
-    testoutput_for_prop $1 "dynstat_uvel_max" "U maximum" $2; umax=$?
-    testoutput_for_prop $1 "dynstat_uvel_mean" "U mean" $2; umean=$?
-    testoutput_for_prop $1 "dynstat_uvel_sd" "U s.d." $2; usd=$?
-    testoutput_for_prop $1 "dynstat_vvel_min" "V minimum" $2; vmin=$?
-    testoutput_for_prop $1 "dynstat_vvel_max" "V maximum" $2; vmax=$?
-    testoutput_for_prop $1 "dynstat_vvel_mean" "V mean" $2; vmean=$?
-    testoutput_for_prop $1 "dynstat_vvel_sd" "V s.d." $2; vsd=$?
-    
-    dashnum $cg2dres $tmin $tmax $tmean $tsd $smin $smax $smean $ssd \
-        $umin $umax $umean $usd $vmin $vmax $vmean $vsd
 }
 
 genmakemodel()
@@ -191,7 +210,13 @@ genmakemodel()
 	GENMAKE2="$BASH ../../../tools/genmake2"
 	(
 	    cd $1;
-	    command="$GENMAKE2  -ds -m $MAKE --mods=../code"
+	    command="$GENMAKE2  -ds -m $MAKE"
+	    if test "x$ADM" = x ; then
+		command="$command --mods=../code"
+	    else
+		command="$command --mods=../code_ad"
+		command="$command -adof=../../../tools/adjoint_options/adjoint_staf"
+	    fi
 	    if test "x$OPTFILE" != xNONE ; then
 		command="$command --optfile=$OPTFILE"
 	    fi
@@ -272,7 +297,11 @@ makemodel()
 	cd $1;
 	if test -r Makefile ; then
 	    printf 'make ... ' 1>&2
-	    $MAKE >> make.log 2>&1
+	    if test "x$ADM" = x ; then
+		$MAKE >> make.log 2>&1
+	    else
+		$MAKE adall >> make.log 2>&1
+	    fi
 	    RETVAL=$?
 	    if test "x$RETVAL" != x0 ; then
 		tail make.log
@@ -294,12 +323,27 @@ linkdata()
     if test "x$1" = x1 ; then
 	(
 	    cd $2
-	    files=`( cd ../input ; ls -1 | grep -v CVS )`
-	    for i in $files ; do
-		if test ! -d "../input/"$i ; then
-		    ln -sf "../input/"$i $i
-		fi
-	    done
+	    if test "x$ADM" = x ; then
+		files=`( cd ../input ; ls -1 | grep -v CVS )`
+		for i in $files ; do
+		    if test ! -d "../input/"$i ; then
+			ln -sf "../input/"$i $i
+		    fi
+		done
+	    else
+		files=`( cd ../input ; ls -1 *.bin | grep -v CVS )`
+		for i in $files ; do
+		    if test ! -d "../input/"$i ; then
+			ln -sf "../input/"$i $i
+		    fi
+		done
+		files=`( cd ../input_ad ; ls -1 | grep -v CVS )`
+		for i in $files ; do
+		    if test ! -d "../input_ad/"$i ; then
+			ln -sf "../input_ad/"$i $i
+		    fi
+		done
+	    fi
 	)
     fi
 }
@@ -308,7 +352,7 @@ runmodel()
 {
     # runmodel directory
     #
-    #  runs "$COMMAND" in "directory" 
+    #  runs "$COMMAND in "directory" 
     #  (where "$COMMAND" is relative to "directory")
     (
 	cd $1
@@ -318,7 +362,11 @@ runmodel()
 	RETVAL=$?
 	if test "x$RETVAL" = x0 ; then
 	    echo successful 1>&2
-	    cp output.txt $CDIR"/output.txt"
+	    if test "x$ADM" = x ; then
+		cp output.txt $CDIR"/output.txt"
+	    else
+		cp output.txt_adm $CDIR"/output.txt_adm"
+	    fi
 	    return 0
 	else
 	    tail run.log
@@ -456,9 +504,11 @@ TESTDIRS=
 MPACKDIR="../tools/mpack-1.6"
 HAVE_MPACK=
 MPACK="$MPACKDIR/mpack"
-COMMAND="make output.txt"
+COMMAND=
 MAKE=make
 MPI=f
+
+ADM=
 
 echo -n "parsing options...  "
 
@@ -523,6 +573,8 @@ for ac_option ; do
 
 	-mpi) MPI=t ;;
 
+	-adm | -ad) ADM=t ;;
+
 	-ieee) IEEE=true ;;
 	-noieee) IEEE= ;;
 
@@ -556,6 +608,14 @@ fi
 
 if test "x$OPTFILE" = xNONE -a "x$MITGCM_OF" != x ; then
     OPTFILE=$MITGCM_OF
+fi
+
+if test "x$ADM" = xt -a "x$COMMAND" = x ; then
+    COMMAND="./mitgcmuv_ad > output.txt_adm 2>&1"
+fi
+
+if test "x$COMMAND" = x ; then
+    COMMAND="make output.txt"
 fi
 
 echo "OK"
@@ -615,7 +675,8 @@ else
 fi
 echo
 echo >> $SUMMARY
-cat << EOF | tee -a $SUMMARY
+if test "x$ADM" = x ; then
+    cat << EOF | tee -a $SUMMARY
                 T           S           U           V
 G D M    c        m  s        m  s        m  s        m  s
 E p a R  g  m  m  e  .  m  m  e  .  m  m  e  .  m  m  e  .
@@ -623,6 +684,17 @@ N n k u  2  i  a  a  d  i  a  a  d  i  a  a  d  i  a  a  d
 2 d e n  d  n  x  n  .  n  x  n  .  n  x  n  .  n  x  n  .
 
 EOF
+else
+    echo "ADJOINT=true" >> $SUMMARY
+    echo >> $SUMMARY
+    cat << EOF | tee -a $SUMMARY
+G D M    C  G
+E p a R  o  r
+N n k u  s  a
+2 d e n  t  d
+
+EOF
+fi
 
 #  ...and each test directory...
 for dir in $TESTDIRS ; do
@@ -640,8 +712,14 @@ for dir in $TESTDIRS ; do
 
     #  Verify that the testdir exists and contains previous 
     #  results in the correct location--or skip this directory!
-    if test ! -r $dir"/results/output.txt" ; then
-	echo "can't read \"$dir/results/output.txt\" -- skipping $dir"
+    fout=
+    if test "x$ADM" = x ; then
+	fout=$dir"/results/output.txt"
+    else
+	fout=$dir"/results_ad/output.txt_adm"
+    fi
+    if test ! -r $fout ; then
+	echo "can't read \"$fout\" -- skipping $dir"
 	continue
     fi
 
@@ -662,7 +740,11 @@ for dir in $TESTDIRS ; do
 	linkdata $use_seperate_build $dir/$rundir
     fi
     
-    CODE_DIR=$dir/code
+    if test "x$ADM" = x ; then
+	CODE_DIR=$dir/code
+    else
+	CODE_DIR=$dir/code_ad
+    fi
     BUILD_DIR=$dir/$builddir
     MPI_FILES="CPP_EEOPTIONS.h_mpi SIZE.h_mpi"
     NOMPI_FILES="CPP_EEOPTIONS.h_nompi SIZE.h_nompi"
@@ -720,7 +802,12 @@ for dir in $TESTDIRS ; do
     fi
     
     echo
-    fres=`formatresults $dir ${genmake:-N} ${makedepend:-N} ${make:-N} ${run:-N} $results`
+    if test "x$ADM" = x ; then
+	fres=`formatresults $dir ${genmake:-N} ${makedepend:-N} ${make:-N} ${run:-N} $results`
+    else
+	fres=`printf '%s %s %s %s' ${genmake:-N} ${makedepend:-N} ${make:-N} ${run:-N}`
+	fres=$fres"$results   $dir"
+    fi
     echo
     echo "$fres" >> $SUMMARY
     echo "fresults='$fres'" > $CDIR"/summary.txt"
