exit if "cvs update" command does not return normally

diff --git a/tools/example_scripts/ACESgrid/aces_test_adm_mpi b/tools/example_scripts/ACESgrid/aces_test_adm_mpi
--- a/tools/example_scripts/ACESgrid/aces_test_adm_mpi
+++ b/tools/example_scripts/ACESgrid/aces_test_adm_mpi
@@ -6,7 +6,7 @@
 #PBS -e /home/jmc/test_ACES/output/tst_adm.stderr
 #PBS -o /home/jmc/test_ACES/output/tst_adm.stdout
 
-# $Header: /u/gcmpack/MITgcm/tools/example_scripts/ACESgrid/Attic/aces_test_adm_mpi,v 1.10 2011/01/21 17:17:28 jmc Exp $
+# $Header: /u/gcmpack/MITgcm/tools/example_scripts/ACESgrid/Attic/aces_test_adm_mpi,v 1.11 2011/08/17 20:45:35 jmc Exp $
 # $Name:  $
 
 # ACES-grid PBS-batch script for Adjoint MPI test using ifort (default=v8) & mpich
@@ -58,6 +58,11 @@ if [ $checkOut -eq 1 ] ; then
 #   ( cd $gcmDIR/verification ; ../tools/do_tst_2+2 -clean )
     echo "cvs update of dir $gcmDIR :"
     ( cd $gcmDIR ; cvs -q -d :pserver:cvsanon@mitgcm.org:/u/gcmpack update -P -d ) 2>&1
+    RETVAL=$?
+    if test "x$RETVAL" != x0 ; then
+       echo " cvs update fail (return val=$RETVAL) => exit"
+       exit
+    fi
   else
     echo "no dir: $gcmDIR/CVS => try a fresh check-out"
     checkOut=2
@@ -71,16 +76,18 @@ if [ $checkOut -eq 2 ] ; then
   cvs -d :pserver:cvsanon@mitgcm.org:/u/gcmpack co -P -d $gcmDIR MITgcm > /dev/null 2>&1
   /usr/bin/find $gcmDIR -type d | xargs chmod g+rxs
   /usr/bin/find $gcmDIR -type f | xargs chmod g+r
-else
-  if test -e $gcmDIR/verification ; then
-     echo "dir $gcmDIR/verification exist"
-  else
-     echo "no dir $gcmDIR/verification => exit"
-     exit
-  fi
 fi
 
-cd $gcmDIR/verification
+#- change dir to $gcmDIR/verification dir:
+if test -e $gcmDIR/verification ; then
+  if [ $checkOut -lt 2 ] ; then
+    echo " dir $gcmDIR/verification exist" ; fi
+  cd $gcmDIR/verification
+else
+  echo "no dir $gcmDIR/verification => exit"
+  exit
+fi
+
 echo ./testreport $options -of $OPTFILE -command \"$EXE\" -odir aces-$sfx
 ./testreport $options -of $OPTFILE -command "$EXE" -odir aces-$sfx
 
diff --git a/tools/example_scripts/ACESgrid/test_aces_gnu_mpi b/tools/example_scripts/ACESgrid/test_aces_gnu_mpi
--- a/tools/example_scripts/ACESgrid/test_aces_gnu_mpi
+++ b/tools/example_scripts/ACESgrid/test_aces_gnu_mpi
@@ -6,7 +6,7 @@
 #PBS -e /mit/jm_c/test_acesgrid/output/tst_gnu.stderr
 #PBS -o /mit/jm_c/test_acesgrid/output/tst_gnu.stdout
 
-# $Header: /u/gcmpack/MITgcm/tools/example_scripts/ACESgrid/Attic/test_aces_gnu_mpi,v 1.2 2011/08/10 23:32:51 jmc Exp $
+# $Header: /u/gcmpack/MITgcm/tools/example_scripts/ACESgrid/Attic/test_aces_gnu_mpi,v 1.3 2011/08/17 20:45:35 jmc Exp $
 # $Name:  $
 
 if test -f /etc/profile.d/modules.sh ; then
@@ -55,6 +55,11 @@ if [ $checkOut -eq 1 ] ; then
 #   ( cd $gcmDIR/verification ; ../tools/do_tst_2+2 -clean )
     echo "cvs update of dir $gcmDIR :"
     ( cd $gcmDIR ; cvs -q -d :pserver:cvsanon@mitgcm.org:/u/gcmpack update -P -d ) 2>&1
+    RETVAL=$?
+    if test "x$RETVAL" != x0 ; then
+       echo " cvs update fail (return val=$RETVAL) => exit"
+       exit
+    fi
   else
     echo "no dir: $gcmDIR/CVS => try a fresh check-out"
     checkOut=2
@@ -68,16 +73,18 @@ if [ $checkOut -eq 2 ] ; then
   cvs -d :pserver:cvsanon@mitgcm.org:/u/gcmpack co -P -d $gcmDIR MITgcm > /dev/null 2>&1
   /usr/bin/find $gcmDIR -type d | xargs chmod g+rxs
   /usr/bin/find $gcmDIR -type f | xargs chmod g+r
-else
-  if test -e $gcmDIR/verification ; then
-     echo "dir $gcmDIR/verification exist"
-  else
-     echo "no dir $gcmDIR/verification => exit"
-     exit
-  fi
 fi
 
-cd $gcmDIR/verification
+#- change dir to $gcmDIR/verification dir:
+if test -e $gcmDIR/verification ; then
+  if [ $checkOut -lt 2 ] ; then
+    echo " dir $gcmDIR/verification exist" ; fi
+  cd $gcmDIR/verification
+else
+  echo "no dir $gcmDIR/verification => exit"
+  exit
+fi
+
 # avoid hanging in fizhi-cs-32x32x40 (due to I/O problems with g77)
 echo ./testreport $options -of $OPTFILE -command \"$EXE\" -odir acesgrid-$sfx \
  -skd fizhi-cs-32x32x40
