same changes as for acesgrid.org testing script (but keep running  testreport in home dir)

diff --git a/tools/example_scripts/ACESgrid/aces_test_adm_mpi b/tools/example_scripts/ACESgrid/aces_test_adm_mpi
--- a/tools/example_scripts/ACESgrid/aces_test_adm_mpi
+++ b/tools/example_scripts/ACESgrid/aces_test_adm_mpi
@@ -6,7 +6,7 @@
 #PBS -e /home/jmc/test_aces/output/tst_adm.stderr
 #PBS -o /home/jmc/test_aces/output/tst_adm.stdout
 
-# $Header: /u/gcmpack/MITgcm/tools/example_scripts/ACESgrid/Attic/aces_test_adm_mpi,v 1.23 2013/08/20 18:53:11 jmc Exp $
+# $Header: /u/gcmpack/MITgcm/tools/example_scripts/ACESgrid/Attic/aces_test_adm_mpi,v 1.24 2014/05/07 16:22:24 jmc Exp $
 # $Name:  $
 
 # ACES-grid PBS-batch script for Adjoint MPI test using ifort (default=v8) & mpich
@@ -17,15 +17,29 @@ fi
 # Note: added "ulimit -s unlimited" in file "~/.bashrc"
 # to pass big test (the 2 fizhi-cs-* test & adjoint tests) with MPI
 
-dNam='aces'
-TST_DIR="$HOME/test_$dNam"
-echo "start from TST_DIR='$TST_DIR' at: "`date`
-
 umask 0022
 #- to get case insensitive "ls" (and order of tested experiments)
 export LC_ALL="en_US.UTF-8"
+echo " running on: "`hostname`
 
-HERE=$TST_DIR/output
+dNam='aces'
+HERE="$HOME/test_$dNam"
+SavD="$HERE/send"
+SEND="ssh geo $SavD/mpack"
+TST_DIR=$HERE
+
+if test -d $TST_DIR ; then
+  echo "start from TST_DIR='$TST_DIR' at: "`date`
+else
+# if test ! -d /scratch/jm_c ; then mkdir /scratch/jm_c ; fi
+  if test ! -d $TST_DIR ; then mkdir $TST_DIR ; fi
+  if test ! -d $TST_DIR ; then
+    echo "ERROR: Can't create directory \"$TST_DIR\""
+    exit 1
+  fi
+  echo "start in new dir TST_DIR='$TST_DIR' at: "`date`
+fi
+
 sfx='adm'
  module add mpich/intel
  module add netcdf/3.6.1/icc
@@ -38,7 +52,7 @@ sfx='adm'
  export PATH="$PATH:$HOME/bin"
 
 #- keep a copy of MPI_MFILE:
-cp -p $PBS_NODEFILE $HERE"/mf_"$sfx
+cp -p $PBS_NODEFILE $HERE"/output/mf_"$sfx
 
 checkOut=1 ; options="$options -do"
 #options="$options -nc" ; checkOut=0
@@ -113,9 +127,6 @@ else
   echo "no dir: $gcmDIR/verification => exit"
   exit
 fi
-
-SavD="$HOME/test_$dNam/send"
-SEND="ssh geo $SavD/mpack"
 
 echo ./testreport $options -of $OPTFILE -command \"$EXE\" -odir ${dNam}-$sfx \
   -send \"$SEND\" -sd $SavD -a jmc@mitgcm.org
diff --git a/tools/example_scripts/ACESgrid/aces_test_g77_adm b/tools/example_scripts/ACESgrid/aces_test_g77_adm
--- a/tools/example_scripts/ACESgrid/aces_test_g77_adm
+++ b/tools/example_scripts/ACESgrid/aces_test_g77_adm
@@ -6,7 +6,7 @@
 #PBS -e /home/jmc/test_aces/output/tst_g77.stderr
 #PBS -o /home/jmc/test_aces/output/tst_g77.stdout
 
-# $Header: /u/gcmpack/MITgcm/tools/example_scripts/ACESgrid/Attic/aces_test_g77_adm,v 1.16 2013/08/20 18:53:11 jmc Exp $
+# $Header: /u/gcmpack/MITgcm/tools/example_scripts/ACESgrid/Attic/aces_test_g77_adm,v 1.17 2014/05/07 16:22:24 jmc Exp $
 # $Name:  $
 
 # ACES-grid PBS-batch script for Adjoint test using g77 compiler
@@ -15,15 +15,29 @@ if test -f /etc/profile.d/modules.sh ; then
     . /etc/profile.d/modules.sh
 fi
 
-dNam='aces'
-TST_DIR="$HOME/test_$dNam"
-echo "start from TST_DIR='$TST_DIR' at: "`date`
-
 umask 0022
 #- to get case insensitive "ls" (and order of tested experiments)
 export LC_ALL="en_US.UTF-8"
+echo " running on: "`hostname`
 
-HERE=$TST_DIR/output
+dNam='aces'
+HERE="$HOME/test_$dNam"
+SavD="$HERE/send"
+SEND="ssh geo $SavD/mpack"
+TST_DIR=$HERE
+
+if test -d $TST_DIR ; then
+  echo "start from TST_DIR='$TST_DIR' at: "`date`
+else
+# if test ! -d /scratch/jm_c ; then mkdir /scratch/jm_c ; fi
+  if test ! -d $TST_DIR ; then mkdir $TST_DIR ; fi
+  if test ! -d $TST_DIR ; then
+    echo "ERROR: Can't create directory \"$TST_DIR\""
+    exit 1
+  fi
+  echo "start in new dir TST_DIR='$TST_DIR' at: "`date`
+fi
+
 sfx='g77'
 #module add gnu
 #module add netcdf/3.6.1/icc
@@ -34,7 +48,7 @@ sfx='g77'
  export PATH="$PATH:$HOME/bin"
 
 #- keep a copy of MPI_MFILE:
-cp -p $PBS_NODEFILE $HERE"/mf_"$sfx
+cp -p $PBS_NODEFILE $HERE"/output/mf_"$sfx
 
 checkOut=1 ; options="$options -do"
 #options="$options -nc" ; checkOut=0
@@ -109,9 +123,6 @@ else
   echo "no dir: $gcmDIR/verification => exit"
   exit
 fi
-
-SavD="$HOME/test_$dNam/send"
-SEND="ssh geo $SavD/mpack"
 
 echo ./testreport $options -of $OPTFILE -odir ${dNam}-$sfx \
   -send \"$SEND\" -sd $SavD -a jmc@mitgcm.org
diff --git a/tools/example_scripts/ACESgrid/aces_test_ifc_mp2 b/tools/example_scripts/ACESgrid/aces_test_ifc_mp2
--- a/tools/example_scripts/ACESgrid/aces_test_ifc_mp2
+++ b/tools/example_scripts/ACESgrid/aces_test_ifc_mp2
@@ -6,7 +6,7 @@
 #PBS -e /home/jmc/test_aces/output/tst_mp2.stderr
 #PBS -o /home/jmc/test_aces/output/tst_mp2.stdout
 
-# $Header: /u/gcmpack/MITgcm/tools/example_scripts/ACESgrid/Attic/aces_test_ifc_mp2,v 1.1 2013/09/29 15:32:11 jmc Exp $
+# $Header: /u/gcmpack/MITgcm/tools/example_scripts/ACESgrid/Attic/aces_test_ifc_mp2,v 1.2 2014/05/07 16:22:24 jmc Exp $
 # $Name:  $
 
 # ACES-grid PBS-batch script for MPI+Multi-Threaded test using ifort (v9) & mpich2
@@ -17,15 +17,29 @@ fi
 # Note: added "ulimit -s unlimited" in file "~/.bashrc"
 # to pass big test (the 2 fizhi-cs-* test & adjoint tests) with MPI
 
-dNam='aces'
-TST_DIR="$HOME/test_$dNam"
-echo "start from TST_DIR='$TST_DIR' at: "`date`
-
 umask 0022
 #- to get case insensitive "ls" (and order of tested experiments)
 export LC_ALL="en_US.UTF-8"
+echo " running on: "`hostname`
 
-HERE=$TST_DIR/output
+dNam='aces'
+HERE="$HOME/test_$dNam"
+SavD="$HERE/send"
+SEND="ssh geo $SavD/mpack"
+TST_DIR=$HERE
+
+if test -d $TST_DIR ; then
+  echo "start from TST_DIR='$TST_DIR' at: "`date`
+else
+# if test ! -d /scratch/jm_c ; then mkdir /scratch/jm_c ; fi
+  if test ! -d $TST_DIR ; then mkdir $TST_DIR ; fi
+  if test ! -d $TST_DIR ; then
+    echo "ERROR: Can't create directory \"$TST_DIR\""
+    exit 1
+  fi
+  echo "start in new dir TST_DIR='$TST_DIR' at: "`date`
+fi
+
 sfx='mp2'
 #- to build:
  module add ifc/9.0.021 icc/9.0.021 intel/9.0
@@ -42,7 +56,7 @@ sfx='mp2'
 #export KMP_STACKSIZE=400m  <-- added in file "~/.bashrc"
 
 #- keep a copy of MPI_MFILE:
-cp -p $PBS_NODEFILE $HERE"/mf_"$sfx
+cp -p $PBS_NODEFILE $HERE"/output/mf_"$sfx
 
 checkOut=1 ; options="$options -do"
 #options="$options -nc" ; checkOut=0
@@ -125,9 +139,6 @@ if test -x $HERE/$check_sh ; then
    mv -f $HERE/${check_sh}.log $HERE/${check_sh}.log_bak
    ( cd $HERE ; ./$check_sh > ${check_sh}.log 2>&1 ) &
 fi
-
-SavD="$HOME/test_$dNam/send"
-SEND="ssh geo $SavD/mpack"
 
 echo ./testreport $options -of $OPTFILE -command \"$EXE\" -odir ${dNam}-$sfx \
   -send \"$SEND\" -sd $SavD -a jmc@mitgcm.org
diff --git a/tools/example_scripts/ACESgrid/aces_test_ifc_mth b/tools/example_scripts/ACESgrid/aces_test_ifc_mth
--- a/tools/example_scripts/ACESgrid/aces_test_ifc_mth
+++ b/tools/example_scripts/ACESgrid/aces_test_ifc_mth
@@ -6,7 +6,7 @@
 #PBS -e /home/jmc/test_aces/output/tst_mth.stderr
 #PBS -o /home/jmc/test_aces/output/tst_mth.stdout
 
-# $Header: /u/gcmpack/MITgcm/tools/example_scripts/ACESgrid/Attic/aces_test_ifc_mth,v 1.28 2013/08/20 18:53:11 jmc Exp $
+# $Header: /u/gcmpack/MITgcm/tools/example_scripts/ACESgrid/Attic/aces_test_ifc_mth,v 1.29 2014/05/07 16:22:24 jmc Exp $
 # $Name:  $
 
 if test -f /etc/profile.d/modules.sh ; then
@@ -15,15 +15,29 @@ fi
 # Note: added "ulimit -s unlimited" in file "~/.bashrc"
 # to pass big test (the 2 fizhi-cs-* test & adjoint tests) with MPI
 
-dNam='aces'
-TST_DIR="$HOME/test_$dNam"
-echo "start from TST_DIR='$TST_DIR' at: "`date`
-
 umask 0022
 #- to get case insensitive "ls" (and order of tested experiments)
 export LC_ALL="en_US.UTF-8"
+echo " running on: "`hostname`
 
-HERE=$TST_DIR/output
+dNam='aces'
+HERE="$HOME/test_$dNam"
+SavD="$HERE/send"
+SEND="ssh geo $SavD/mpack"
+TST_DIR=$HERE
+
+if test -d $TST_DIR ; then
+  echo "start from TST_DIR='$TST_DIR' at: "`date`
+else
+# if test ! -d /scratch/jm_c ; then mkdir /scratch/jm_c ; fi
+  if test ! -d $TST_DIR ; then mkdir $TST_DIR ; fi
+  if test ! -d $TST_DIR ; then
+    echo "ERROR: Can't create directory \"$TST_DIR\""
+    exit 1
+  fi
+  echo "start in new dir TST_DIR='$TST_DIR' at: "`date`
+fi
+
 sfx='mth'
  module add ifc/9.0.021 icc/9.0.021 intel/9.0
  module add netcdf/3.6.1/icc
@@ -33,7 +47,7 @@ sfx='mth'
  export KMP_STACKSIZE=400m
 
 #- keep a copy of MPI_MFILE:
-cp -p $PBS_NODEFILE $HERE"/mf_"$sfx
+cp -p $PBS_NODEFILE $HERE"/output/mf_"$sfx
 
 checkOut=1 ; #options="$options -do"
 #options="$options -nc" ; checkOut=0
@@ -108,9 +122,6 @@ else
   echo "no dir: $gcmDIR/verification => exit"
   exit
 fi
-
-SavD="$HOME/test_$dNam/send"
-SEND="ssh geo $SavD/mpack"
 
 echo ./testreport $options -of $OPTFILE -odir ${dNam}-$sfx \
   -send \"$SEND\" -sd $SavD -a jmc@mitgcm.org
