keep error from cvs command ; check for return value of "cvs co"

diff --git a/tools/example_scripts/ACESgrid/test_aces_ifc_adm b/tools/example_scripts/ACESgrid/test_aces_ifc_adm
--- a/tools/example_scripts/ACESgrid/test_aces_ifc_adm
+++ b/tools/example_scripts/ACESgrid/test_aces_ifc_adm
@@ -6,7 +6,7 @@
 #PBS -e /mit/jm_c/test_acesgrid/output/tst_iad.stderr
 #PBS -o /mit/jm_c/test_acesgrid/output/tst_iad.stdout
 
-# $Header: /u/gcmpack/MITgcm/tools/example_scripts/ACESgrid/Attic/test_aces_ifc_adm,v 1.10 2015/01/10 20:12:25 jmc Exp $
+# $Header: /u/gcmpack/MITgcm/tools/example_scripts/ACESgrid/Attic/test_aces_ifc_adm,v 1.11 2015/01/16 21:57:33 jmc Exp $
 # $Name:  $
 
 if test -f /etc/profile.d/modules.sh ; then
@@ -90,7 +90,7 @@ if [ $checkOut -eq 1 ] ; then
     echo ' remove all Makefile_syntax and do "cvs update -P -d"'
     ( cd $gcmDIR/verification ; rm -f */build/Makefile_syntax )
 #   echo "cvs update of dir $gcmDIR :"
-    ( cd $gcmDIR ; cvs -q $cvsArg update -P -d ) 2>&1
+    ( cd $gcmDIR ; cvs -q $cvsArg update -P -d )
     RETVAL=$?
     if test "x$RETVAL" != x0 ; then
        echo "cvs update on '"`hostname`"' fail (return val=$RETVAL) => exit"
@@ -106,14 +106,21 @@ if [ $checkOut -eq 2 ] ; then
      rm -rf $gcmDIR
   fi
 # cvs co MITgcm
-  cvs $cvsArg co -P -d $gcmDIR MITgcm > /dev/null 2>&1
-  for exp2add in $addExp ; do
-   echo " add dir: $exp2add (from Contrib:verification_other)"
-   ( cd $gcmDIR/verification ; cvs $cvsArg co -P -d $exp2add \
-                  MITgcm_contrib/verification_other/$exp2add > /dev/null 2>&1 )
-  done
-  /usr/bin/find $gcmDIR -type d | xargs chmod g+rxs
-  /usr/bin/find $gcmDIR -type f | xargs chmod g+r
+  cvs $cvsArg co -P -d $gcmDIR MITgcm > /dev/null
+  RETVAL=$?
+  if test "x$RETVAL" != x0 ; then
+      echo "cvs co on '"`hostname`"' fail (return val=$RETVAL) => exit"
+      exit
+  fi
+  if test -d $gcmDIR/verification ; then
+    for exp2add in $addExp ; do
+      echo " add dir: $exp2add (from Contrib:verification_other)"
+      ( cd $gcmDIR/verification ; cvs $cvsArg co -P -d $exp2add \
+                     MITgcm_contrib/verification_other/$exp2add > /dev/null )
+    done
+    /usr/bin/find $gcmDIR -type d | xargs chmod g+rxs
+    /usr/bin/find $gcmDIR -type f | xargs chmod g+r
+  fi
 fi
 
 #- change dir to $gcmDIR/verification dir:
