run testreport on local /scratch disk (instead of on /data) and move back scripts and log file to home dir (previously also on /data).

diff --git a/tools/example_scripts/ACESgrid/test_aces_op64_tuv b/tools/example_scripts/ACESgrid/test_aces_op64_tuv
--- a/tools/example_scripts/ACESgrid/test_aces_op64_tuv
+++ b/tools/example_scripts/ACESgrid/test_aces_op64_tuv
@@ -3,10 +3,10 @@
 #PBS -q one
 #PBS -N tst_tuv
 #PBS -l nodes=1:ppn=2
-#PBS -e /data/jm_c/test_acesgrid/output/tst_tuv.stderr
-#PBS -o /data/jm_c/test_acesgrid/output/tst_tuv.stdout
+#PBS -e /mit/jm_c/test_acesgrid/output/tst_tuv.stderr
+#PBS -o /mit/jm_c/test_acesgrid/output/tst_tuv.stdout
 
-# $Header: /u/gcmpack/MITgcm/tools/example_scripts/ACESgrid/Attic/test_aces_op64_tuv,v 1.14 2014/03/18 18:50:56 jmc Exp $
+# $Header: /u/gcmpack/MITgcm/tools/example_scripts/ACESgrid/Attic/test_aces_op64_tuv,v 1.15 2014/05/07 16:16:04 jmc Exp $
 # $Name:  $
 
 if test -f /etc/profile.d/modules.sh ; then
@@ -15,15 +15,29 @@ fi
 # Note: added "ulimit -s unlimited" in file "~/.tcshrc"
 # to pass big test (the 2 fizhi-cs-* test & adjoint tests) with MPI
 
-dNam='acesgrid'
-TST_DIR="/data/jm_c/test_$dNam"
-echo "start from TST_DIR='$TST_DIR' at: "`date`
-
 umask 0022
 #- to get case insensitive "ls" (and order of tested experiments)
 export LC_ALL="en_US.UTF-8"
+echo " running on: "`hostname`
 
-HERE=$TST_DIR/output
+dNam='acesgrid'
+HERE="$HOME/test_$dNam"
+SavD="$HERE/send"
+SEND="ssh login $SavD/mpack"
+TST_DIR="/scratch/jm_c/test_$dNam"
+
+if test -d $TST_DIR ; then
+  echo "start from TST_DIR='$TST_DIR' at: "`date`
+else
+  if test ! -d /scratch/jm_c ; then mkdir /scratch/jm_c ; fi
+  if test ! -d $TST_DIR ; then mkdir $TST_DIR ; fi
+  if test ! -d $TST_DIR ; then
+    echo "ERROR: Can't create directory \"$TST_DIR\""
+    exit 1
+  fi
+  echo "start in new dir TST_DIR='$TST_DIR' at: "`date`
+fi
+
 sfx='tuv'
  module add open64
  OPTFILE="../tools/build_options/linux_amd64_open64"
@@ -40,10 +54,10 @@ dAlt=`date +%d` ; dAlt=`expr $dAlt % 3`
 if [ $dAlt -eq 1 ] ; then options="-adm -do -devel" ; fi
 
 #- keep a copy of MPI_MFILE:
-cp -p $PBS_NODEFILE $HERE"/mf_"$sfx
+cp -p $PBS_NODEFILE $HERE"/output/mf_"$sfx
 
-checkOut=1
-#options="$options -nc" ; checkOut=0
+checkOut=2
+#options="$options -nc" ; checkOut=1
 #options="$options -q"  ; checkOut=0
 
 addExp=0
@@ -54,7 +68,7 @@ cd $TST_DIR
 #dsp=`df -P . | tail -1 | awk '{print $5}' | sed 's/%$//'`
 #if [ $dsp -gt 99 ] ; then
 dsp=`df -P . | tail -1 | awk '{print $4}'`
-if [ $dsp -le 200000000 ] ; then
+if [ $dsp -le 100000000 ] ; then
   echo 'Not enough space on this disk => do not run testreport.'
   df .
   exit
@@ -113,9 +127,6 @@ else
   echo "no dir: $gcmDIR/verification => exit"
   exit
 fi
-
-SavD="$HOME/test_$dNam/send"
-SEND="ssh login $SavD/mpack"
 
 echo ./testreport $options -of $OPTFILE -odir ${dNam}-$sfx \
   -send \"$SEND\" -sd $SavD -a jmc@mitgcm.org
diff --git a/tools/example_scripts/ACESgrid/test_aces_pgi_mpi b/tools/example_scripts/ACESgrid/test_aces_pgi_mpi
--- a/tools/example_scripts/ACESgrid/test_aces_pgi_mpi
+++ b/tools/example_scripts/ACESgrid/test_aces_pgi_mpi
@@ -3,10 +3,10 @@
 #PBS -q one
 #PBS -N tst_pgi
 #PBS -l nodes=1:ppn=6
-#PBS -e /data/jm_c/test_acesgrid/output/tst_pgi.stderr
-#PBS -o /data/jm_c/test_acesgrid/output/tst_pgi.stdout
+#PBS -e /mit/jm_c/test_acesgrid/output/tst_pgi.stderr
+#PBS -o /mit/jm_c/test_acesgrid/output/tst_pgi.stdout
 
-# $Header: /u/gcmpack/MITgcm/tools/example_scripts/ACESgrid/Attic/test_aces_pgi_mpi,v 1.16 2014/03/18 18:50:56 jmc Exp $
+# $Header: /u/gcmpack/MITgcm/tools/example_scripts/ACESgrid/Attic/test_aces_pgi_mpi,v 1.17 2014/05/07 16:16:04 jmc Exp $
 # $Name:  $
 
 if test -f /etc/profile.d/modules.sh ; then
@@ -15,30 +15,45 @@ fi
 # Note: added "ulimit -s unlimited" in file "~/.bashrc"
 # to pass big test (the 2 fizhi-cs-* test & adjoint tests) with MPI
 
-dNam='acesgrid'
-TST_DIR="/data/jm_c/test_$dNam"
-echo "start from TST_DIR='$TST_DIR' at: "`date`
-
 umask 0022
 #- to get case insensitive "ls" (and order of tested experiments)
 export LC_ALL="en_US.UTF-8"
+echo " running on: "`hostname`
 
-HERE=$TST_DIR/output
+dNam='acesgrid'
+HERE="$HOME/test_$dNam"
+SavD="$HERE/send"
+SEND="ssh login $SavD/mpack"
+TST_DIR="/scratch/jm_c/test_$dNam"
+
+if test -d $TST_DIR ; then
+  echo "start from TST_DIR='$TST_DIR' at: "`date`
+else
+  if test ! -d /scratch/jm_c ; then mkdir /scratch/jm_c ; fi
+  if test ! -d $TST_DIR ; then mkdir $TST_DIR ; fi
+  if test ! -d $TST_DIR ; then
+    echo "ERROR: Can't create directory \"$TST_DIR\""
+    exit 1
+  fi
+  echo "start in new dir TST_DIR='$TST_DIR' at: "`date`
+fi
+
 sfx='pgi'
  module add pgi
  module add mvapich
 #module add mvapich2
  OPTFILE="../tools/build_options/linux_amd64_pgf77"
  options="-j 2 -MPI 6"
+ EXE="mpirun -v -all-local -np TR_NPROC ./mitgcmuv"
 
 dAlt=`date +%d` ; dAlt=`expr $dAlt % 3`
 if [ $dAlt -eq 1 ] ; then options="$options -fast" ; fi
 
 #- keep a copy of MPI_MFILE:
-cp -p $PBS_NODEFILE $HERE"/mf_"$sfx
+cp -p $PBS_NODEFILE $HERE"/output/mf_"$sfx
 
-checkOut=1
-#options="$options -nc" ; checkOut=0
+checkOut=2
+#options="$options -nc" ; checkOut=1
 #options="$options -q"  ; checkOut=0
 
 addExp=0
@@ -49,7 +64,7 @@ cd $TST_DIR
 #dsp=`df -P . | tail -1 | awk '{print $5}' | sed 's/%$//'`
 #if [ $dsp -gt 99 ] ; then
 dsp=`df -P . | tail -1 | awk '{print $4}'`
-if [ $dsp -le 200000000 ] ; then
+if [ $dsp -le 100000000 ] ; then
   echo 'Not enough space on this disk => do not run testreport.'
   df .
   exit
@@ -109,17 +124,14 @@ else
   exit
 fi
 
-SavD="$HOME/test_$dNam/send"
-SEND="ssh login $SavD/mpack"
-
-echo ./testreport $options -of $OPTFILE -odir ${dNam}-$sfx \
+echo ./testreport $options -of $OPTFILE -command \"$EXE\" -odir ${dNam}-$sfx \
   -send \"$SEND\" -sd $SavD -a jmc@mitgcm.org
-./testreport $options -of $OPTFILE -odir ${dNam}-$sfx \
+./testreport $options -of $OPTFILE -command "$EXE" -odir ${dNam}-$sfx \
   -send "$SEND" -sd $SavD -a jmc@mitgcm.org
 
 echo ''
-echo ../tools/do_tst_2+2 -mpi -o ${dNam}-$sfx \
+echo ../tools/do_tst_2+2 -mpi -exe \"$EXE\" -o ${dNam}-$sfx \
   -send \"$SEND\" -sd $SavD -a jmc@mitgcm.org
-../tools/do_tst_2+2 -mpi -o ${dNam}-$sfx \
+../tools/do_tst_2+2 -mpi -exe "$EXE" -o ${dNam}-$sfx \
   -send "$SEND" -sd $SavD -a jmc@mitgcm.org
 
