o make it easy to specify the "cyrus" makedepend

diff --git a/tools/genmake2 b/tools/genmake2
--- a/tools/genmake2
+++ b/tools/genmake2
@@ -1,6 +1,6 @@
 #! /usr/bin/env bash
 #
-# $Header: /u/gcmpack/MITgcm/tools/genmake2,v 1.89 2004/07/21 16:34:46 edhill Exp $
+# $Header: /u/gcmpack/MITgcm/tools/genmake2,v 1.90 2004/07/27 20:59:19 edhill Exp $
 #
 # Makefile generator for MITgcm UV codes
 #   created  by cnh 03/98
@@ -195,29 +195,47 @@ EOF
 	    echo "    a system-default makedepend was not found."
 	    
 	    #  Try to build the cyrus implementation
-	    rm -f ./genmake_cy_md
-	    (
-		cd $ROOTDIR/tools/cyrus-imapd-makedepend  \
-		    &&  ./configure > /dev/null 2>&1  \
-		    &&  make > /dev/null 2>&1
-		if test -x ./makedepend.exe ; then
-		    $LN ./makedepend.exe ./makedepend
-		fi
-		./makedepend ifparser.c > /dev/null 2>&1  \
-		    &&  echo "true"
-	    ) > ./genmake_cy_md
-	    grep true ./genmake_cy_md > /dev/null 2>&1
+	    build_cyrus_makedepend
 	    RETVAL=$?
-	    if test "x$RETVAL" = x0 ; then
-		MAKEDEPEND='$(TOOLSDIR)/cyrus-imapd-makedepend/makedepend'
-	    else
+	    if test "x$RETVAL" != x0 ; then
 		MAKEDEPEND='$(TOOLSDIR)/xmakedepend'
 	    fi
 	    rm -f ./genmake_cy_md
 	fi
+    else
+	#  echo "MAKEDEPEND=${MAKEDEPEND}"
+	echo "${MAKEDEPEND}" | grep -i cyrus > /dev/null 2>&1
+	RETVAL=$?
+	if test x"$RETVAL" = x0 ; then
+	    build_cyrus_makedepend
+	fi
     fi
 }
 
+
+build_cyrus_makedepend()  {
+    rm -f ./genmake_cy_md
+    (
+	cd $ROOTDIR/tools/cyrus-imapd-makedepend  \
+	    &&  ./configure > /dev/null 2>&1  \
+	    &&  make > /dev/null 2>&1
+	if test -x ./makedepend.exe ; then
+	    $LN ./makedepend.exe ./makedepend
+	fi
+	./makedepend ifparser.c > /dev/null 2>&1  \
+	    &&  echo "true"
+    ) > ./genmake_cy_md
+    grep true ./genmake_cy_md > /dev/null 2>&1
+    RETVAL=$?
+    rm -f ./genmake_cy_md
+    if test "x$RETVAL" = x0 ; then
+	MAKEDEPEND='$(TOOLSDIR)/cyrus-imapd-makedepend/makedepend'
+	return 0
+    else
+	echo "WARNING: unable to build cyrus-imapd-makedepend"
+	return 1
+    fi
+}
 
 # Guess possible config options for this host
 find_possible_configs()  {
@@ -672,7 +690,7 @@ PACKAGES=
 ENABLE=
 DISABLE=
 MAKEFILE=
-MAKEDEPEND=
+#MAKEDEPEND=
 PDEPEND=
 DUMPSTATE=t
 PDEFAULT=
