Added backup selection of xmakedepend in TOOLSDIR for occasions when makedepend does not exist on the system (e.g. new and partial Linux installs).

diff --git a/tools/genmake2 b/tools/genmake2
--- a/tools/genmake2
+++ b/tools/genmake2
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# $Header: /u/gcmpack/MITgcm/tools/genmake2,v 1.32 2003/11/12 22:05:47 edhill Exp $
+# $Header: /u/gcmpack/MITgcm/tools/genmake2,v 1.33 2003/11/13 15:10:40 adcroft Exp $
 #
 # Makefile generator for MITgcm UV codes
 #   created  by cnh 03/98
@@ -102,6 +102,16 @@ find_possible_configs()  {
 
     if test "x$CPP" = x ; then
 	CPP="cpp -traditional -P"
+    fi
+
+    # makedepend is not always available
+    if test "x${MAKEDEPEND}" = x ; then
+      which makedepend >& /dev/null
+      RETVAL=$?
+      if test "x${RETVAL}" = x1 ; then
+         echo "    makedepend was not found. Using xmakedpend instead."
+         MAKEDEPEND='$(TOOLSDIR)/xmakedepend'
+      fi
     fi
 
     # look for possible fortran compilers
