o first check-in for the "branch-genmake2" merge  o verification suite as run on shelley (gcc 3.2.2):
Wed Oct  8 23:42:29 EDT 2003
                T           S           U           V
G D M    c        m  s        m  s        m  s        m  s
E p a R  g  m  m  e  .  m  m  e  .  m  m  e  .  m  m  e  .
N n k u  2  i  a  a  d  i  a  a  d  i  a  a  d  i  a  a  d
2 d e n  d  n  x  n  .  n  x  n  .  n  x  n  .  n  x  n  .

OPTFILE=NONE

Y Y Y Y 13 16 16 16  0 16 16 16 16 16 16 16 16 13 12  0  0 pass  adjustment.128x64x1
Y Y Y Y 16 16 16 16  0 16 16 16 16 16 16  0  0 16 16  0  0 pass  adjustment.cs-32x32x1
Y Y Y Y 16 16 16 16  0 16 16 16 16 16 16 22  0 16 16 22  0 pass  adjust_nlfs.cs-32x32x1
Y Y Y Y -- 13 13 16 16 13 13 13 13 16 16 16 16 16 16 16 16 N/O   advect_cs
Y Y Y Y -- 22 16 16 16 16 16 16 13 16 16 16 16 16 16 16 16 N/O   advect_xy
Y Y Y Y -- 13 16 13 16 16 16 16 16 16 16 22 16 16 16 16 16 N/O   advect_xz
Y Y Y Y 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 pass  aim.5l_cs
Y Y Y Y 14 16 16 16 16 16 16 16 16 13 16 16 16 16 16 13 16 pass  aim.5l_Equatorial_Channel
Y Y Y Y 16 16 16 16 16 16 16 16 16 16 16 13 16 16 13 13 16 pass  aim.5l_LatLon
Y Y Y Y 13 16 16 16 16 16 16 16 16 16 13 12 13 13 16 13 16 pass  exp0
Y Y Y Y 14 16 16 16 16 16 16 16 22 16 16 16 13 16 16 22 16 pass  exp1
Y Y Y Y 13 13 16 13 16 16 16 16 16 13 13 16 16 13 13 13 13 pass  exp2
Y Y Y Y 16 16 16 16 16 16 16 16 22 16 16 16 16 16 16 16 16 pass  exp4
Y Y Y Y 16 16 16 16 16 16 16 16 16 16 16 22 16 16 16 22 16 pass  exp5
Y Y Y Y 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 pass  front_relax
Y Y Y Y 14 16 16 13 13 16 16 13 13 16 13 13 16 12 13 13 16 pass  global_ocean.90x40x15
Y Y Y Y 10 16 16 13 13 16 13 16 16 13 13 13 13 16 16 13 16 FAIL  global_ocean.cs32x15
Y Y Y Y  6 11 12 13 13 12 13 16 13  9  9  9  9 10  9  9 11 FAIL  global_ocean_pressure
Y Y Y Y 14 16 16 13 16 16 16 13 13 13 13 13 16 12 16 13 16 pass  global_with_exf
Y Y Y Y 14 16 16 16 16 16 16 16 16 11 13 22 13 16 16  9 16 pass  hs94.128x64x5
Y Y Y Y 13 16 16 16 16 16 16 16 16 11 16 16 16 13 16 22 13 pass  hs94.1x64x5
Y Y Y Y 14 16 16 16 16 16 16 16 16 13 16 13 13 16 16 22 13 pass  hs94.cs-32x32x5
Y Y Y Y 10 10 16 13 13 16 16 16 22 16 13 13 13 13 13 22 13 FAIL  ideal_2D_oce
Y Y Y Y  8 16 16 16 16 16 16 16 16 13 13  8 16 16 16 16 16 FAIL  internal_wave
Y Y Y Y 14 16 16 16 16 16 16 16 16 13 13 22 13 13 13 22 16 pass  inverted_barometer
Y Y Y Y 12 16 16 16 16 16 16 16 16 16 13 12 13 13 13 13 13 FAIL  lab_sea
Y Y Y Y 11 16 16 16 16 16 16 16 13 13 13 12 13 16 13 12 13 FAIL  natl_box
Y Y Y Y 16 16 16 16 16 16 16 16 22 16 16 16 16 16 16 16 16 pass  plume_on_slope
Y Y Y Y 13 16 16 16 16 13 16 16 16 16 16 16 16 13 16 16 16 pass  solid-body.cs-32x32x1

diff --git a/tools/genmake2 b/tools/genmake2
--- a/tools/genmake2
+++ b/tools/genmake2
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# $Header: /u/gcmpack/MITgcm/tools/genmake2,v 1.11 2003/09/29 16:15:23 edhill Exp $
+# $Header: /u/gcmpack/MITgcm/tools/genmake2,v 1.12 2003/10/09 04:19:20 edhill Exp $
 #
 # Makefile generator for MITgcm UV codes
 #   created  by cnh 03/98
@@ -8,13 +8,71 @@
 #   modified by aja 01/00
 #   rewritten in bash by eh3 08/03
 
+# Search for particular CPP #cmds associated with packages
+# usage: test_for_package_in_cpp_options CPP_file package_name
+test_for_package_in_cpp_options() {
+    cpp_options=$1
+    pkg=$2
+    grep -i "#define.*ALLOW_$pkg" $cpp_options > /dev/null 2>&1
+    RETVAL=$?
+    if test "x${RETVAL}" = x0 ; then
+	echo "Error: In $cpp_options there is an illegal line: #define ALLOW_$pkg"
+	exit 99
+    fi
+    grep -i "#undef.*ALLOW_$pkg" $cpp_options > /dev/null 2>&1
+    RETVAL=$?
+    if test "x${RETVAL}" = x0 ; then
+	echo "Error: In $cpp_options there is an illegal line: #undef ALLOW_$pkg"
+	exit 99
+    fi
+    grep -i "#define.*DISABLE_$pkg" $cpp_options > /dev/null 2>&1
+    RETVAL=$?
+    if test "x${RETVAL}" = x0 ; then
+	echo "Error: In $cpp_options there is an illegal line: #define DISABLE_$pkg"
+	exit 99
+    fi
+    grep -i "#undef.*DISABLE_$pkg" $cpp_options > /dev/null 2>&1
+    RETVAL=$?
+    if test "x${RETVAL}" = x0 ; then
+	echo "Error: In $cpp_options there is an illegal line: #undef DISABLE_$pkg"
+	exit 99
+   fi
+}
+
+# Read the $ROOTDIR/pkg/pkg_groups file and expand any references to
+# the package list.
+expand_pkg_groups() {
+    new_packages=
+    PKG_GROUPS=$ROOTDIR"/pkg/pkg_groups"
+    if test -r $PKG_GROUPS ; then
+	cat $PKG_GROUPS | sed -e 's/#.*$//g' | sed -e 's/:/ : /g' > ./p1.tmp
+	cat ./p1.tmp | awk '(NF>2 && $2==":"){ print $0 }' > ./p2.tmp
+	matched=0
+	for i in $PACKAGES ; do
+	    line=`grep "^ *$i" ./p2.tmp`
+	    RETVAL=$?
+	    if test "x$RETVAL" = x0 ; then
+		matched=1
+		replace=`echo $line | awk '{ $1=""; $2=""; print $0 }'`
+		echo "    replacing \"$i\" with: $replace"
+		new_packages="$new_packages $replace"
+	    else
+		new_packages="$new_packages $i"
+	    fi
+	done
+	PACKAGES=$new_packages
+	rm -f ./p[1,2].tmp
+    else
+	echo "Warning: can't read package groups definition file: $PKG_GROUPS"
+    fi
+}
 
 # Guess possible config options for this host
 find_possible_configs()  {
 
     tmp1=`uname`"_"`uname -m`
     tmp2=`echo $tmp1 | sed -e 'y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/'`
-    PLATFORM=`echo $tmp2 | sed -e 's/i[3-6]86/ia32/'`
+    PLATFORM=`echo $tmp2 | sed -e 's/i[3-6]86/ia32/' | sed -e 's/athlon/ia32/'`
     OFLIST=`(cd $ROOTDIR/tools/build_options; ls | grep "^$PLATFORM")`
     echo "  The platform appears to be:  $PLATFORM"
 #     if test "x$OFLIST" = x ; then
@@ -181,6 +239,8 @@ usage()  {
     echo "      -disable=NAME | --disable=NAME"
     echo "    -enable NAME | --enable NAME"
     echo "      -enable=NAME | --enable=NAME"
+    echo "    -standarddirs NAME | --standarddirs NAME"
+    echo "      -standarddirs=NAME | --standarddirs=NAME"
     echo "    -noopt NAME | --noopt NAME"
     echo "      -noopt=NAME | --noopt=NAME"
 #    echo "    -cpp NAME | --cpp NAME"
@@ -255,6 +315,7 @@ MODS=
 TOOLSDIR=
 SOURCEDIRS=
 INCLUDEDIRS=
+STANDARDDIRS=
 
 PWD=`pwd`
 MAKE=make
@@ -265,23 +326,34 @@ MACHINE=`uname -a`
 EXECUTABLE=
 EXEHOOK=
 EXEDIR=
+PACKAGES_CONF=
+IEEE=
+if test "x$MITGCM_IEEE" != x ; then
+    IEEE=$MITGCM_IEEE
+fi
 
 #  The following state can be set directly by command-line switches
 gm_s1="OPTFILE PDEPEND PDEFAULT MAKEFILE PLATFORM ROOTDIR MODS DISABLE ENABLE NOOPT"
-gm_s2="FC IEEE MPI JAM DUMPSTATE"
+gm_s2="FC IEEE MPI JAM DUMPSTATE STANDARDDIRS"
 
 #  The following state is not directly set by command-line switches
 gm_s3="LN S64 KPP LINK PACKAGES MAKEDEPEND PDEPEND PDEFAULT INCLUDES FFLAGS FOPTIM "
 gm_s4="CFLAGS KFLAGS1 KFLAGS2 LIBS KPPFILES NOOPTFILES NOOPTFLAGS"
 gm_s5="TOOLSDIR SOURCEDIRS INCLUDEDIRS PWD MAKE THISHOSTNAME THISDATE MACHINE"
-gm_s6="EXECUTABLE EXEHOOK EXEDIR"
+gm_s6="EXECUTABLE EXEHOOK EXEDIR PACKAGES_CONF"
 
 gm_state="COMMANDL $gm_s1 $gm_s2 $gm_s3 $gm_s4 $gm_s5 $gm_s6"
 
 
 echo
 echo "===  Processing options files and arguments  ==="
-gm_local="./gm_local"
+gm_local="genmake_local"
+for i in . $MODS ; do
+    if test -r $i/$gm_local ; then
+	source $i/$gm_local
+	break
+    fi
+done
 echo -n "  getting local config information:  "
 if test -e $gm_local ; then
     echo "using $gm_local"
@@ -373,6 +445,11 @@ for ac_option ; do
 	-enable=* | --enable=*)
 	    ENABLE=$ac_optarg ;;
 	
+	-standarddirs | --standarddirs)
+	    ac_prev=STANDARDDIRS ;;
+	-standarddirs=* | --standarddirs=*)
+	    STANDARDDIRS=$ac_optarg ;;
+
 	-noopt | --noopt)
 	    ac_prev=NOOPT ;;
 	-noopt=* | --noopt=*)
@@ -389,14 +466,14 @@ for ac_option ; do
 	    FC=$ac_optarg ;;
 	
 	-ieee | --ieee)
-	    IEEE=1 ;;
+	    IEEE=true ;;
 	-noieee | --noieee)
-	    IEEE=0 ;;
+	    IEEE= ;;
 	
 	-mpi | --mpi)
-	    MPI=1 ;;
+	    MPI=true ;;
 	-nompi | --nompi)
-	    MPI=0 ;;
+	    MPI= ;;
 	
 	-jam | --jam)
 	    JAM=1 ;;
@@ -419,6 +496,18 @@ for ac_option ; do
     esac
     
 done
+
+if test -f ./.genmakerc ; then
+    echo
+    echo "WARNING: genmake2 has detected a copy of the old-style \"./.genmakerc\""
+    echo "  file.  This file format is no longer supported.  Please see:"
+    echo 
+    echo "    http://mitgcm.org/devel_HOWTO/"
+    echo
+    echo "  for directions on how to setup and use the new \"genmake2\" input"
+    echo "  files and send an email to MITgcm-support@mitgcm.org if you want help."
+    echo 
+fi
 
 if test "x${ROOTDIR}" = x ; then
     if test "${PWD##/*/}" = "bin" -a -d ../model -a -d ../eesup -a -d ../pkg ; then
@@ -466,7 +555,7 @@ if test "x$OPTFILE" != xNONE ; then
 	    exit 1
 	fi
 	if test "x$DUMPSTATE" != xf ; then
-	    cp -f $OPTFILE "gm_optfile"
+	    cp -f $OPTFILE "genmake_optfile"
 	fi
     else
 	echo "Error: can't read OPTFILE=\"$OPTFILE\""
@@ -482,7 +571,7 @@ if test "x$FC" = x ; then
 Error: no Fortran compiler: please specify using one of the following:
   1) within the options file ("FC=...") as specified by "-of=OPTFILE"
   2) the "-fc=XXX" command-line option
-  3) the "./gm_local" file
+  3) the "./genmake_local" file
 EOF
     exit 1
 fi
@@ -500,7 +589,7 @@ if test "x$RETVAL" != x0 ; then
 Error: C pre-processor "$CPP" failed the test case: please specify using:
 
   1) within the options file ("CPP=...") as specified by "-of=OPTFILE"
-  2) the "./gm_local" file
+  2) the "./genmake_local" file
 
 EOF
     exit 1
@@ -603,7 +692,18 @@ fi
 source ./.pd_tmp
 rm -f ./.pd_tmp
 
+#  Search for default packages.  Note that a "$ROOTDIR/pkg/pkg_groups"
+#  file should eventually be added so that, for convenience, one can 
+#  specify groups of packages using names like "ocean" and "atmosphere".
 echo  -n "  checking default package list:  "
+if test "x${PDEFAULT}" = x ; then
+    for i in "." $MODS ; do
+	if test -r $i"/packages.conf" ; then
+		PDEFAULT=$i"/packages.conf"
+		break
+	fi
+    done
+fi
 if test "x${PDEFAULT}" = x ; then
     PDEFAULT="$ROOTDIR/pkg/pkg_default"
 fi
@@ -626,7 +726,9 @@ else
 	for i in $def ; do
 	    PACKAGES="$PACKAGES $i"
 	done
-	echo "    packages are:  $PACKAGES"
+	echo "    before group expansion packages are: $PACKAGES"
+	expand_pkg_groups
+	echo "    after group expansion packages are:  $PACKAGES"
     fi
 fi
 
@@ -645,7 +747,7 @@ for p in $PACKAGES ; do
 done
 PACKAGES="$pack"
 echo "  applying ENABLE settings"
-rm -f ./.tmp_pack
+echo "" > ./.tmp_pack
 PACKAGES="$PACKAGES $ENABLE"
 for i in $PACKAGES ; do
     if test ! -d "$ROOTDIR/pkg/$i" ; then
@@ -761,39 +863,17 @@ done
 # done
 # echo
 
-echo "  Searching for CPP_OPTIONS.h (macros and flags for configuring the model):"
-CPP_OPTIONS=
-spaths=". $SOURCEDIRS"
-for i in $spaths ; do
-    try="$i/CPP_OPTIONS.h"
-    #  echo -n "    trying $try : "
-    if test -f $try -a -r $try ; then
-	echo "    found CPP_OPTIONS=\"$try\""
-	CPP_OPTIONS="$try"
-	if test "x$i" != "x." ; then
-	    cp -f $CPP_OPTIONS .
-	fi
-	break
-    fi
-done
-if test "x$CPP_OPTIONS" = x ; then
-    echo "Error: can't find \"CPP_OPTIONS.h\" in the path list: $spaths"
-    exit 1
-fi
-if test -e CPP_OPTIONS.h ; then
-    if test ! -e CPP_OPTIONS.h.bak ; then
-	cp -f CPP_OPTIONS.h CPP_OPTIONS.h.bak
-    fi
-    cat CPP_OPTIONS.h \
-	| awk 'BEGIN{p=1;} ($1=="C===" && $2=="GENMAKE"){p=0;} {if (p==1) print $0}' \
-	> CPP_OPTIONS.h.tmp
-fi
-cat <<EOF >>CPP_OPTIONS.h.tmp
+# Create a list of #define and #undef to enable/disable packages
+PACKAGES_DOT_H=PACKAGES_CONFIG.h
+cat <<EOF >$PACKAGES_DOT_H".tmp"
 C=== GENMAKE v2 ===
 C  The following defines have been set by GENMAKE, so please do not
 C  edit anything below these comments.  In general, you should
 C  add or remove packages by re-running genmake with different 
 C  "-enable" and/or "-disable" options.
+
+#ifndef PACKAGES_H
+#define PACKAGES_H
 
 C  Packages disabled by genmake:
 EOF
@@ -814,7 +894,8 @@ for n in $names ; do
 	done
 	if test "x$has_pack" = xf ; then
 	    undef=`echo "ALLOW_$n" | awk '{print toupper($0)}'`
-	    echo "#undef $undef" >> CPP_OPTIONS.h.tmp
+	    echo "#undef $undef" >> $PACKAGES_DOT_H".tmp"
+#           DEFINES="$DEFINES -U$undef"
 
 #EH3  WARNING :  This is an UGLY HACK that needs to be removed!!!
 	    case $n in 
@@ -823,9 +904,6 @@ for n in $names ; do
 		    ;;
 		mom_vecinv)
 		    DEFINES="$DEFINES -DDISABLE_MOM_VECINV"
-		    ;;
-		generic_advdiff)
-		    DEFINES="$DEFINES -DDISABLE_GENERIC_ADVDIFF"
 		    ;;
 		debug)
 		    DEFINES="$DEFINES -DDISABLE_DEBUGMODE"
@@ -836,28 +914,49 @@ for n in $names ; do
 	fi
     fi
 done
-cat <<EOF >>CPP_OPTIONS.h.tmp
+cat <<EOF >>$PACKAGES_DOT_H".tmp"
 
 C  Packages enabled by genmake:
 EOF
 for i in $PACKAGES ; do
     def=`echo "ALLOW_$i" | awk '{print toupper($0)}'`
-    echo "#define $def" >> CPP_OPTIONS.h.tmp
+    echo "#define $def" >> $PACKAGES_DOT_H".tmp"
+#eh3 DEFINES="$DEFINES -D$def"
 
 #EH3  WARNING :  This is an UGLY HACK that needs to be removed!!!
     case $i in 
 	aim_v23)
-	    echo "#define   ALLOW_AIM" >> CPP_OPTIONS.h.tmp
+	    echo "#define   ALLOW_AIM" >> $PACKAGES_DOT_H".tmp"
+	    DEFINES="$DEFINES -DALLOW_AIM"
+	    echo "Warning: ALLOW_AIM is set to enable aim_v23. This is REALLY ugly Jean-Michel :-)"
 	    ;;
     esac
 #EH3  WARNING :  This is an UGLY HACK that needs to be removed!!!
 
 done
-mv -f CPP_OPTIONS.h.tmp CPP_OPTIONS.h
+cat <<EOF >>$PACKAGES_DOT_H".tmp"
+
+#endif /* PACKAGES_H */
+EOF
+
+if test ! -f $PACKAGES_DOT_H ; then
+    mv -f $PACKAGES_DOT_H".tmp" $PACKAGES_DOT_H
+else
+    cmp $PACKAGES_DOT_H".tmp" $PACKAGES_DOT_H
+    RETVAL=$?
+    if test "x$RETVAL" = x0 ; then
+	rm -f $PACKAGES_DOT_H".tmp"
+    else
+	mv -f $PACKAGES_DOT_H $PACKAGES_DOT_H".bak"
+	mv -f $PACKAGES_DOT_H".tmp" $PACKAGES_DOT_H
+    fi
+fi
 
 echo "  Adding STANDARDDIRS"
 BUILDDIR=${BUILDDIR:-.}
-STANDARDDIRS=${STANDARDDIRS:-"eesupp model"}
+if test "x$STANDARDDIRS" = x ; then
+    STANDARDDIRS="eesupp model"
+fi
 for d in $STANDARDDIRS ; do
     adr="$ROOTDIR/$d/src"
     if test ! -d $adr ; then
@@ -877,14 +976,37 @@ for d in $STANDARDDIRS ; do
     fi
 done
 
+echo " Searching for CPP_OPTIONS.h in order to warn about the presence"
+echo " of \"#define ALLOW_PKGNAME\"-type statements:"
+CPP_OPTIONS=
+spaths=". $INCLUDEDIRS"
+for i in $spaths ; do
+    try="$i/CPP_OPTIONS.h"
+    #  echo -n "    trying $try : "
+    if test -f $try -a -r $try ; then
+	echo "    found CPP_OPTIONS=\"$try\""
+	CPP_OPTIONS="$try"
+	break
+    fi
+done
+if test "x$CPP_OPTIONS" = x ; then
+    echo "Error: can't find \"CPP_OPTIONS.h\" in the path list: $spaths"
+    exit 1
+fi
+# New safety test: make sure packages are not mentioned in CPP_OPTIONS.h
+names=`ls -1 "$ROOTDIR/pkg"`
+for n in $names ; do
+    test_for_package_in_cpp_options $CPP_OPTIONS $n
+done
+
 
 echo
 echo "===  Creating the Makefile  ==="
 echo "  setting INCLUDES"
 for i in $INCLUDEDIRS ; do
-    if test -d $i ; then
-	INCLUDES="$INCLUDES -I$i"
-    else
+    if ! test -d $i ; then
+#	INCLUDES="$INCLUDES -I$i"
+#   else
 	echo "Warning: can't find INCLUDEDIRS=\"$i\""
     fi
 done
@@ -1064,13 +1186,13 @@ clean:
 Clean:
 	@make clean
 	@make cleanlinks
-	-rm -f Makefile.bak
+	-rm -f Makefile.bak genmake_state genmake_optfile make.log
 CLEAN:
 	@make Clean
 	-find \$(EXEDIR) -name "*.meta" -exec rm {} \;
 	-find \$(EXEDIR) -name "*.data" -exec rm {} \;
 	-find \$(EXEDIR) -name "fort.*" -exec rm {} \;
-	-rm -f \$(EXECUTABLE)
+	-rm -f \$(EXECUTABLE) output.txt
 
 makefile:
 	${0} $@
@@ -1134,10 +1256,10 @@ printf "\n===  Done  ===\n"
 
 #  Write the "state" for future records
 if test "x$DUMPSTATE" != xf ; then
-    echo -n "" > gm_state
+    echo -n "" > genmake_state
     for i in $gm_state ; do
 	t1="t2=\$$i"
 	eval $t1
-	echo "$i='$t2'" >> gm_state
+	echo "$i='$t2'" >> genmake_state
     done
 fi
diff --git a/verification/testreport b/verification/testreport
--- a/verification/testreport
+++ b/verification/testreport
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-#  $Header: /u/gcmpack/MITgcm/verification/testreport,v 1.9 2003/09/16 18:16:03 edhill Exp $
+#  $Header: /u/gcmpack/MITgcm/verification/testreport,v 1.10 2003/10/09 04:19:20 edhill Exp $
 #
 
 usage()
@@ -11,6 +11,7 @@ usage()
     echo "where possible OPTIONS are:"
     echo "  (-help|-h)               print usage"
     echo "  (-mpi)                   use MPI input files"
+    echo "  (-ieee|-noieee)          if possible, use IEEE compiler flags"
     echo "  (-optfile=|-of=)STRING   list of optfiles to use"
     echo "  (-a|-addr)STRING         list of email recipients"
     echo "                             (DEF=\"edhill@mitgcm.org\")"
@@ -18,10 +19,15 @@ usage()
     echo "                             (DEF=\"\" which builds all)"
     echo "  (-b|-bash)STRING         location of \"bash\" executable"
     echo "                             (DEF=\"\" for \"/bin/bash\")"
-    echo "  (-c|-command)STRING      command to run"
+    echo "  (-command)STRING         command to run"
     echo "                             (DEF=\"make output.txt\")"
     echo "  (-m|-make)STRING         command to use for \"make\""
     echo "                             (DEF=\"make\")"
+    echo "  (-clean)                 *ONLY* run \"make CLEAN\""
+    echo "  (-quick|-q)              same as \"-nogenmake -noclean -nodepend\""
+    echo "  (-nogenmake|-ng)         skip the genmake stage"
+    echo "  (-noclean|-nc)           skip the \"make clean\" stage"
+    echo "  (-nodepend|-nd)          skip the \"make depend\" stage"
     echo
     echo "and where STRING follows a whitespace-delimited format"
     echo "such as:"
@@ -174,70 +180,90 @@ testoutput()
 genmakemodel()
 {
     # genmakemodel directory
-    GENMAKE2="$BASH ../../../tools/genmake2"
-    (
-	cd $1;
-	printf 'genmake ... ' 1>&2
-        # ../../../tools/genmake -ieee -mods=../code > make.log 2>&1
-	$GENMAKE2  -ds -m $MAKE --mods=../code "--optfile="$OPTFILE > make.log 2>&1
-	RETVAL=$?
-	for i in gm_state gm_optfile gm_local Makefile ; do
-	    if test -r $i ; then
-		cp $i $CDIR
+    if test "x$NOGENMAKE" = xt ; then
+	echo "genmake skipped!"
+    else
+	GENMAKE2="$BASH ../../../tools/genmake2"
+	(
+	    cd $1;
+	    command="$GENMAKE2  -ds -m $MAKE --mods=../code"
+	    if test "x$OPTFILE" != xNONE ; then
+		command="$command --optfile=$OPTFILE"
+		# echo "  command=\"$command\""
 	    fi
-	done
-	if test "x$RETVAL" != x0 ; then
-	    tail make.log
-	    echo "genmakemodel: genmake failed" 1>&2
-	    cp make.log $CDIR
-	    return 1
-	else
-	    echo "succesful" 1>&2
-	fi
-    )
+	    if test "x$IEEE" != x ; then
+		command="$command -ieee"
+	    fi
+	    # echo "command: \"$command\""
+	    printf 'genmake ... ' 1>&2
+	    $command > make.log 2>&1
+	    RETVAL=$?
+	    for i in genmake_state genmake_optfile genmake_local Makefile ; do
+		if test -r $i ; then
+		    cp $i $CDIR
+		fi
+	    done
+	    if test "x$RETVAL" != x0 ; then
+		tail make.log
+		echo "genmakemodel: genmake failed" 1>&2
+		cp make.log $CDIR
+		return 1
+	    else
+		echo "succesful" 1>&2
+	    fi
+	)
+    fi
 }
 
 makeclean()
 {
     # makeclean directory
-    (
-	cd $1;
-	if test -e output.txt ; then
-	    rm -f output.txt
-	fi
-	printf 'make CLEAN ... ' 2>&1
-	if test -r Makefile ; then
-	    $MAKE CLEAN >> make.log 2>&1
-	    RETVAL=$?
-	    if test "x$RETVAL" != x0 ; then
-		tail make.log
-		echo "makeclean: \"make CLEAN\" failed" 1>&2
-		cp make.log $CDIR"/make.log"
-		return 1
+    if test "x$NOCLEAN" = xt ; then
+	echo "make CLEAN skipped!"
+    else
+	(
+	    cd $1;
+	    if test -e output.txt ; then
+		rm -f output.txt
 	    fi
-	fi
-	echo succesful 1>&2
-	exit 0
-    )
+	    printf 'make CLEAN ... ' 2>&1
+	    if test -r Makefile ; then
+		$MAKE CLEAN >> make.log 2>&1
+		RETVAL=$?
+		if test "x$RETVAL" != x0 ; then
+		    tail make.log
+		    echo "makeclean: \"make CLEAN\" failed" 1>&2
+		    cp make.log $CDIR"/make.log"
+		    return 1
+		fi
+	    fi
+	    echo succesful 1>&2
+	    exit 0
+	)
+    fi
 }
 
 makedependmodel()
 {
     # makedependmodel directory
-    (
-	cd $1;
-	printf 'make depend ... ' 1>&2
-	$MAKE depend >> make.log 2>&1
-	RETVAL=$?
-	if test "x$RETVAL" != x0 ; then
-	    tail make.log
-	    echo "makedependmodel: make depend failed" 1>&2
-	    cp make.log $CDIR"/make.log"
-	    return 1
-	else
-	    echo succesful 1>&2
-	fi
-    )
+    if test "x$NODEPEND" = xt ; then
+	echo "make depend skipped!"
+    else
+	(
+	    cd $1;
+	    printf 'make depend ... ' 1>&2
+	    $MAKE depend >> make.log 2>&1
+	    RETVAL=$?
+	    if test "x$RETVAL" != x0 ; then
+		tail make.log
+		echo "makedependmodel: make depend failed" 1>&2
+		cp make.log $CDIR"/make.log"
+		return 1
+	    else
+		echo succesful 1>&2
+	    fi
+	)
+    fi
 }
 
 makemodel()
@@ -360,14 +386,13 @@ show_help()
 {
     cat - << EOF
 $0 [-help] [-quick] [-verbose] dir1 [dir2] [...]
- -help      Show this help message
- -quick     Skip "genmake" and "make depend" if the Makefile exists
+
+ -help|-h      Show this help message
  -quiet     Reduce the amount of output
  -verbose   Produce copious amounts of output
  -debug     Produce even more output which will mean nothing to most
  -force     Do "make CLEAN" before compiling. This forces a complete rebuild.
  -clean     Do "make CLEAN" after compiling and testing.
- -noieee    By default, $0 uses the -ieee option for genmake. This turns it off.
  -cleanup   Aggresively removes all model output, executables and object files
             and then exits. Use with care.
 
@@ -399,11 +424,22 @@ verbose=1
 clean=0
 expts=''
 # ieee=1
-# quick=0
+
+IEEE=
+if test "x$MITGCM_IEEE" != x ; then
+    IEEE=$MITGCM_IEEE
+fi
+
+
+CLEANUP=f
+QUICK=f
+NOGENMAKE=f
+NOCLEAN=f
+NODEPEND=f
 
 BASH=
-OPTFILES=
-ADDRESSES=edhill@mitgcm.org
+OPTFILE=NONE
+ADDRESSES=
 TESTDIRS=
 MPACKDIR="../tools/mpack-1.6"
 MPACK="$MPACKDIR/mpack"
@@ -431,9 +467,9 @@ for ac_option ; do
 	    usage ;;
 	
 	-optfile | --optfile | -of | --of)
-            ac_prev=OPTFILES ;;
+            ac_prev=OPTFILE ;;
         -optfile=* | --optfile=* | -of=* | --of=*)
-            OPTFILES=$ac_optarg ;;
+            OPTFILE=$ac_optarg ;;
 	
 	-addr | --addr | -a | --a)
             ac_prev=ADDRESSES ;;
@@ -460,10 +496,25 @@ for ac_option ; do
 	-make=* | --make=*)
 	    MAKE=$ac_optarg ;;
 
-	-mpi) MPI=t ;;
+	-clean | --clean)
+	    CLEANUP=t ;;
+
+	-quick | --quick | -q | --q)
+	    QUICK=t ;;
+	-nogenmake | --nogenmake | -ng | --ng)
+	    NOGENMAKE=t ;;
+	-noclean | --noclean | -nc | --nc)
+	    NOCLEAN=t ;;
+	-nodepend | --nodepend | -nd | --nd)
+	    NODEPEND=t ;;
+
+	-mpi) MPI=true ;;
+
+	-ieee) IEEE=true ;;
+	-noieee) IEEE= ;;
+
 	-verbose) verbose=2 ;;
 	-debug) debug=1 ;;
-	-clean) clean=1 ;;
 	-quiet) verbose=0 ;;
 
         -*)
@@ -480,8 +531,18 @@ for ac_option ; do
      
 done
 
+if test "x$QUICK" = xt ; then
+    NOGENMAKE=t
+    NOCLEAN=t
+    NODEPEND=t
+fi
+
 if test "x$TESTDIRS" = x ; then
     TESTDIRS=`scandirs`
+fi
+
+if test "x$OPTFILE" = xNONE -a "x$MITGCM_OF" != x ; then
+    OPTFILE=$MITGCM_OF
 fi
 
 echo "OK"
@@ -522,74 +583,102 @@ EOF
 
 NDIR=0
 
-#  For each optfile...
-for OPTFILE in $OPTFILES ; do
-
-    OPTFILE=`pwd`"/$OPTFILE"
-    if test ! -r $OPTFILE ; then
-	echo "Error: can't read optfile \"$OPTFILE\""
-	exit 1
+if test "x$OPTFILE" != xNONE ; then
+    if test -r $OPTFILE ; then
+	OPTFILE=`pwd`"/$OPTFILE"
     fi
-    echo
-    echo "OPTFILE=$OPTFILE" >> $SUMMARY
-    echo >> $SUMMARY
+fi
+echo
+echo "OPTFILE=$OPTFILE" >> $SUMMARY
+echo >> $SUMMARY
+
+#  ...and each test directory...
+for dir in $TESTDIRS ; do
     
-    #  ...and each test directory...
-    for dir in $TESTDIRS ; do
-
-	#  Verify that the testdir exists and contains previous 
-	#  results in the correct location--or skip this directory!
-	if test ! -r $dir"/results/output.txt" ; then
-	    echo | tee -a $SUMMARY
-	    echo "can't read \"$dir/results/output.txt\" -- skipping $dir" \
-		| tee -a $SUMMARY
-	    continue
+    #  Cleanup only!
+    if test "x$CLEANUP" = xt ; then
+	if test -r $dir/build/Makefile ; then
+	    ( cd $dir/build ; make CLEAN )
 	fi
+	if test -r $dir/input/Makefile ; then
+	    ( cd $dir/input ; make CLEAN )
+	fi
+	continue
+    fi
 
-	#  Is this an MPI run?
-	if test "x$MPI" = xt ; then
-	    if test ! -r $dir"/code/CPP_EEOPTIONS.h_mpi" -o ! -r $dir"/code/SIZE.h_mpi" ; then
-		echo | tee -a $SUMMARY
-		echo "can't read \"$dir/code/CPP_EEOPTIONS.h_mpi\" or \"$dir/code/SIZE.h_mpi\"" \
-		    | tee -a $SUMMARY
-		continue
-	    else
-		cp $dir"/code/CPP_EEOPTIONS.h_mpi" $dir"/code/CPP_EEOPTIONS.h"
-		cp $dir"/code/SIZE.h_mpi" $dir"/code/SIZE.h"
+    #  Verify that the testdir exists and contains previous 
+    #  results in the correct location--or skip this directory!
+    if test ! -r $dir"/results/output.txt" ; then
+	echo "can't read \"$dir/results/output.txt\" -- skipping $dir"
+	continue
+    fi
+
+    echo "-------------------------------------------------------------------------------"
+    echo
+    echo "Experiment:  $dir"
+    echo
+    unset genmake makedepend make run
+    results='-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --'
+
+    if [ -r $dir/build ]; then
+	seperatebuilddir=1
+	builddir=build
+	rundir=build
+	( cd $dir/build; ln -sf ../input/* . )
+    else
+	seperatebuilddir=0
+	builddir=input
+	rundir=input
+    fi
+    
+    CODE_DIR=$dir/code
+    BUILD_DIR=$dir/$builddir
+    MPI_FILES="CPP_EEOPTIONS.h_mpi SIZE.h_mpi"
+    NOMPI_FILES="CPP_EEOPTIONS.h_nompi SIZE.h_nompi"
+
+    #  Is this an MPI run?
+    if test "x$MPI" = xt ; then
+	FILES=$MPI_FILES
+	endings="_mpi"
+    else
+	FILES=$NOMPI_FILES
+	endings="_nompi"
+    fi
+    
+    #  Check to see that we have the files
+    have_files=t
+    for i in $FILES ; do
+	if test ! -r $CODE_DIR/$i ; then
+	    echo "Warning: can't read file $CODE_DIR/$i"
+	    have_files=f
+	fi
+    done
+    if test "x$have_files" != xt -a "x$MPI" = xt ; then
+	echo "Skipping $dir due to lack of input files (see above warning)"
+	continue
+    fi
+    
+    #  If we have the $FILES and they differ, copy the $FILES to $BUILD_DIR
+    if test "x$have_files" = xt ; then
+	for i in $FILES ; do
+	    sstr="s|$endings||"
+	    name=`echo $i | sed -e $sstr `
+	    cmp $CODE_DIR/$i $BUILD_DIR/$name > /dev/null 2>&1
+	    RETVAL=$?
+	    if test "x$RETVAL" != x0 ; then
+		cp $CODE_DIR/$i $BUILD_DIR/$name
 	    fi
-	else
-	    if test -r $dir"/code/CPP_EEOPTIONS.h_nompi" ; then
-		cp $dir"/code/CPP_EEOPTIONS.h_nompi" $dir"/code/CPP_EEOPTIONS.h"
-	    fi
-            if test -r $dir"/code/SIZE.h_nompi" ; then
-                cp $dir"/code/SIZE.h_nompi" $dir"/code/SIZE.h"
-            fi
-	fi
-
-	#  Create an output dir for each OPTFILE/tdir combination
-	CDIR=$DRESULTS"/"$DRESULTS"_"$NDIR
-	mkdir $CDIR
-	CDIR=`pwd`"/$CDIR"
-
-	#  ...configue, make, run, and compare the output.
-	echo "-------------------------------------------------------------------------------"
-	echo
-	echo "Experiment:  $dir"
-	echo
-	unset genmake makedepend make run
-	results='-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --'
-	( cd $dir/input; rm -f *.{o,f,c,F} *.[f,F]90 work* output.txt Make* make.log; )
-	if [ -r $dir/build ]; then
-	    seperatebuilddir=1
-	    builddir=build
-	    rundir=build
-	    ( cd $dir/build; ln -sf ../input/* . )
-	else
-	    seperatebuilddir=0
-	    builddir=input
-	    rundir=input
-	fi
-
+	done
+    fi
+    
+    #  Create an output dir for each OPTFILE/tdir combination
+    CDIR=$DRESULTS"/"$DRESULTS"_"$NDIR
+    mkdir $CDIR
+    CDIR=`pwd`"/$CDIR"
+    
+    if test "x$CLEANUP" = xt ; then
+	makeclean $dir/$builddir
+    else
 	genmakemodel $dir/$builddir && genmake=Y \
 	    && makeclean $dir/$builddir \
 	    && makedependmodel $dir/$builddir && makedepend=Y \
@@ -597,27 +686,32 @@ for OPTFILE in $OPTFILES ; do
 	    && linkdata $seperatebuilddir $dir/$rundir \
 	    && runmodel $dir/$builddir && run=Y \
 	    && results=`testoutput $dir $rundir`
-	echo
-	formatresults $dir ${genmake:-N} ${makedepend:-N} ${make:-N} \
-	    ${run:-N} $results
-	echo
-	formatresults $dir ${genmake:-N} ${makedepend:-N} ${make:-N} \
-	    ${run:-N} $results >> $SUMMARY
-	echo "fresults='" > $CDIR"/summary.txt"
-	formatresults $dir ${genmake:-N} ${makedepend:-N} ${make:-N} \
-	    ${run:-N} $results >> $CDIR"/summary.txt"
-	echo "'" >> $CDIR"/summary.txt"
-	echo "MACH='$MACH'" >> $CDIR"/summary.txt"
-	echo "UNAMEA='$UNAMEA'" >> $CDIR"/summary.txt"
-	echo "DATE='$DATE'" >> $CDIR"/summary.txt"
-	echo "tdir='$dir'" >> $CDIR"/summary.txt"
-
-	(
-	    cd $DRESULTS
-	    tar -cf $NDIR".tar" $DRESULTS"_"$NDIR > /dev/null 2>&1
-	    gzip $NDIR".tar"
-	)
-
+    fi
+    
+    echo
+    formatresults $dir ${genmake:-N} ${makedepend:-N} ${make:-N} \
+	${run:-N} $results
+    echo
+    formatresults $dir ${genmake:-N} ${makedepend:-N} ${make:-N} \
+	${run:-N} $results >> $SUMMARY
+    echo "fresults='" > $CDIR"/summary.txt"
+    formatresults $dir ${genmake:-N} ${makedepend:-N} ${make:-N} \
+	${run:-N} $results >> $CDIR"/summary.txt"
+    echo "'" >> $CDIR"/summary.txt"
+    echo "MACH='$MACH'" >> $CDIR"/summary.txt"
+    echo "UNAMEA='$UNAMEA'" >> $CDIR"/summary.txt"
+    echo "DATE='$DATE'" >> $CDIR"/summary.txt"
+    echo "tdir='$dir'" >> $CDIR"/summary.txt"
+    
+    (
+	cd $DRESULTS
+	tar -cf $NDIR".tar" $DRESULTS"_"$NDIR > /dev/null 2>&1
+	gzip $NDIR".tar"
+    )
+    
+    if test "x$ADDRESSES" = xNONE -o "x$ADDRESSES" = x ; then
+	echo "No mail sent"
+    else
 	$MPACK -s MITgcm-test -m 1000000 $DRESULTS"/"$NDIR".tar.gz" $ADDRESSES
 	RETVAL=$?
 	if test "x$RETVAL" != x0 ; then
@@ -625,10 +719,12 @@ for OPTFILE in $OPTFILES ; do
 	else
 	    rm -f $DRESULTS"/"$NDIR".tar*"
 	fi
+    fi
 
-	NDIR=$(( $NDIR + 1 ))
-	
-    done
+    echo "-------------------------------------------------------------------------------"
+    
+    NDIR=$(( $NDIR + 1 ))
+    
 done
 
 rm tmp_cmpnum.f a.out
