add option "-rootdir"
to be consistent with error message (if not found)

diff --git a/tools/suggest_optfile_names b/tools/suggest_optfile_names
--- a/tools/suggest_optfile_names
+++ b/tools/suggest_optfile_names
@@ -1,24 +1,29 @@
 #! /usr/bin/env bash
 
+#  Explain usage
+usage()
+{
+  echo "Usage: `basename $0` [OPTIONS]"
+  echo "    -> suggest OPTFILE name for MITgcm 'genmake2' script"
+  echo
+  echo "where possible OPTIONS are:"
+  echo "  (-help|-h)		just print this and return"
+  echo "  (-keep|-k)		keep log-file and temp-script file"
+  echo "  (-rootdir NAME | -rd NAME ) Specify the location of"
+  echo "                        the MITgcm Root-Dir as 'NAME'."
+  echo "                 By default, will try to find the location by"
+  echo "                 looking in parent directories (up to the 5th parent)."
+  exit 1
+}
+
 #-- Settings:
-AWK=awk
-keep=0;
-if [ $# -ge 1 ] ; then
-  if test $1 = '-help' -o $1 = '-h' ; then
-    echo "Usage: `basename $0` [-k/-keep]"
-    echo " suggest OPTFILE name for MITgcm 'genmake2' script"
-    echo "options:"
-    echo "  -h/-help :: just print this and return"
-    echo "  -k/-keep :: keep log-file and temp-script file"
-    exit
-  fi
-  if test $1 = '-keep' -o $1 = '-k' ; then keep=1 ; fi
-fi
 LOC_SH_FIND='find_optfile'
 LOGFILE="$LOC_SH_FIND.log"
+AWK=awk
 rm -f $LOC_SH_FIND $LOGFILE
+keep=0;
 
-#-- Get where to find MITgcm main dir (ROOTDIR):
+#-- Set MITgcm Root-Dir (ROOTDIR) from Env.Var. "MITGCM_ROOTDIR":
 if test "x$MITGCM_ROOTDIR" = x ; then
   if test "x$ROOTDIR" != x ; then
     echo "WARNING: Environment Variable 'ROOTDIR' no longer recognized"
@@ -28,7 +33,27 @@ else
   ROOTDIR=$MITGCM_ROOTDIR
 fi
 
-#  Find the MITgcm ${ROOTDIR}
+#-- Parse_options
+yy=
+for xx in "$@" ; do
+
+  # If the previous option needs an argument, assign it.
+  if test -n "$yy"; then
+    eval "$yy=\$xx"
+    yy=
+    continue
+  fi
+
+  case $xx in
+      -help | -h )	usage ;;
+      -rootdir | -rd )	yy=ROOTDIR ;;
+      -keep | -k )	keep=1 ;;
+      *)		echo "Error: unrecognized argument: "$xx
+                        usage ;;
+   esac
+done
+
+#-- Find the MITgcm Root-Dir (${ROOTDIR})
 if test "x${ROOTDIR}" = x ; then
     tmp=`echo $PWD | sed -e 's/\// /g' | $AWK '{print $NR}'`
     if test "x$tmp" = "xbin" -a -d ../model -a -d ../eesupp -a -d ../pkg ; then
@@ -37,7 +62,7 @@ if test "x${ROOTDIR}" = x ; then
         for d in . .. ../.. ../../.. ../../../.. ../../../../.. ; do
             if [ -d "$d/model" -a -d "$d/eesupp" -a -d "$d/pkg" ]; then
                 ROOTDIR=$d
-                printf "Warning: ROOTDIR was not specified ;"
+                printf "Warning: MITgcm Root-Dir was not specified ;"
                 echo " try using a local copy of MITgcm found at \"$ROOTDIR\""
                 break
             fi
@@ -45,13 +70,13 @@ if test "x${ROOTDIR}" = x ; then
     fi
 fi
 if test "x${ROOTDIR}" = x ; then
-    echo "Error: Cannot determine ROOTDIR for MITgcm code."
-    echo "  Please specify a ROOTDIR using either the command line"
+    echo "Error: Cannot determine MITgcm Root-Dir for MITgcm code."
+    echo "  Please specify a Root-Dir using either the command line"
     echo "   option '-rootdir' or the Env.Var. 'MITGCM_ROOTDIR'."
     exit 1
 fi
 if test ! -d ${ROOTDIR} ; then
-    echo "Error: the specified ROOTDIR (\"$ROOTDIR\") does not exist!"
+    echo "Error: the specified MITgcm Root-Dir (\"$ROOTDIR\") does not exist!"
     exit 1
 fi
 
